#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_gtr
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/accessories/tmc2209_sensorless_homing
$CFGDIR/accessories/laser-32bit
$CFGDIR/boards/skr_gtr_dual

opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set Y2_DRIVER_TYPE  "TMC2209"
opt_set Z2_DRIVER_TYPE  "TMC2209"

opt_disable E0_DRIVER_TYPE
opt_disable E1_DRIVER_TYPE
opt_disable E2_DRIVER_TYPE

export PLATFORMIO_ENV=BIGTREE_GTR_V1_0
